version: '2'
services:

  robot-framework:
    build:
      context: ./docker/robot-javafx-demo
    ports:
      - '5900:5900'
    volumes:
      - './src/test/robotframework/:/robot'
      - screen-thing:/tmp/.X11-unix
    networks:
      - testapp

  javafxcompile:
    build:
      context: ./
      dockerfile: Dockerfile_build
    restart: on-failure
    networks:
      - testapp
    volumes:
      - './src/:/src' # ScreenCapturingTest.robot require this.
      - screen-thing:/tmp/.X11-unix
    environment:
      - DISPLAY=:20.0

#  javafxrelease:
#    build:
#      context: ./
#      dockerfile: Dockerfile_release
#    restart: on-failure
#    networks:
#      testapp:
#        aliases:
#         - javafxcompile
#    volumes:
#      - './src/:/src' # ScreenCapturingTest.robot require this.
#      - screen-thing:/tmp/.X11-unix
#    environment:
#      - DISPLAY=:20.0

networks:
  testapp:
volumes:
  screen-thing:
